// 📦 src/utils/constants/uomOptions.js

export const UOM_OPTIONS = [
  { label: "Piece(s)", value: "pcs" },
  { label: "Pack", value: "pack" },
  { label: "Box", value: "box" },
  { label: "Set", value: "set" },
  { label: "Unit", value: "unit" },
  { label: "Pair", value: "pair" },
  { label: "Roll", value: "roll" },
  { label: "Meter", value: "m" },
  { label: "Centimeter", value: "cm" },
  { label: "Millimeter", value: "mm" },
  { label: "Feet", value: "ft" },
  { label: "Inch", value: "in" },
  { label: "Liter", value: "L" },
  { label: "Milliliter", value: "mL" },
  { label: "Kilogram", value: "kg" },
  { label: "Gram", value: "g" },
  { label: "Ton", value: "ton" },
  { label: "Bundle", value: "bundle" },
  { label: "Bottle", value: "bottle" },
  { label: "Can", value: "can" },
  { label: "Jar", value: "jar" },
  { label: "Bag", value: "bag" },
  { label: "Dozen", value: "dozen" },
  { label: "Ream", value: "ream" },
  { label: "Gallon", value: "gal" },
  { label: "Sheet", value: "sheet" },
  { label: "Tablet", value: "tablet" },
  { label: "Sachet", value: "sachet" },
  { label: "Carton", value: "carton" },
  { label: "Rim", value: "rim" },
];
