const useColors = (c) => ({
  cardBg: c.slate.outerBg,
  cardBorder: c.slate.border,
  rowHover: c.slate.itemHover,
  rowBgDisabled: c.slate.hover,
  divider: c.slate.divider,
  rowDivider: c.slate.borderRow,
  inputBg: c.gray.inputBg,
  inputBorder: c.slate.btnBorder,
  inputFocusBorder: c.blue.text,
  textPrimary: c.gray.textPrimary,
  textSecondary: c.gray.textSecondary,
  textMuted: c.gray.textMuted,
  textFaint: c.gray.textDisabled,
  blueText: c.blue.text,
  blueTextAlt: c.blue.textStrong,
  blueBg: c.blue.bg,
  blueBgSoft: c.blue.bgSoft,
  blueBorder: c.blue.border,
  greenText: c.green.text,
  deepBlueText: c.teal.text,
  errorText: c.red.text,
  errorBg: c.red.bg,
  btnBgDisabled: c.slate.btnBg,
  iconMuted: c.slate.mutedColor,
  pendingText: c.orange.text,
  pendingBg: c.orange.bg,
  pendingBorder: c.orange.border,
});

export default useColors;
